# Normal equation
Se puede encontrar una solucion exacta para theta sin necesidad de emplear el gradiente descente de la sesiones pasadas, para ellos se puede encontrar el valor minimo de theta y a partir de alli determinar el valor de theta que minimiza J. 

Los pasos para esta minimizacion se dejan como tarea, y pueden ser calculados según lo siguiente:

Si J es la funcion de coste dada por:

\begin{equation}
J(\theta_1,\theta_2,\theta_3, ...,\theta_n )=\frac{1}{2m} \sum_{i = 1}^m (\Theta^{T} X - \hat{y}^{(i)})^2
\end{equation}


Demostrar que:

- $J(\theta_1,\theta_2,\theta_3, ...,\theta_n ) = \frac{1}{2m} (\Theta ^ T X - y)^T (\Theta ^ T X - y)$

- $ \nabla _{\theta} J = \frac{1}{m}( (X^T X) \Theta - X^T y)$


Para encontrar el valor minimo de \theta,  $\nabla _{\theta} J = 0$, 

- $\Theta = (X^T X)^{-1} X^T y$




Para la demostracion anterior emplee las siguientes propiedades:

- $z^T z= \sum_i z_i^2$
- $a^T b = b^Ta$
- $\nabla _x b^T x = b$
- $\nabla _x  x^T A x = 2Ax$

donde a, b, x son matrices, $\nabla_x$ es la derivada respecto al vector x, y A es una matriz simétrica

1. Para los datos del laboratorio anterior aplicar la ecuacion normal.
2. Tomar el dataset de las casas de Boston y construir un modelo de regresión mutivariada.

```
# Tomar los datos de las casas de boston y hacer una regresion lineal tomando 
# el average number of rooms per dwelling.
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

df = pd.DataFrame({"mean_":target, "rm":data[:,5]})

```

# Intepretación Probabilistica. 

Supongamos que tenemos una caracteristica $x_i$ con m valores de entrenamiento, si asumimos que cada valor $y_i$ presenta una dispersión gaussiana $\epsilon_i$, cada $y_i$ podrá tener el siguiente valor:

$y^{i} = \Theta^T X^{(i)} + \epsilon_i$

Asumiendo ademas que el ruido gaussiando es aleatorio y esta distribuido de forma identica, con media cero y varianza $\sigma$, tenemos que la probabilidad de que la cantidad y tenga  dispersion $\epsilon_i$ es:
\begin{equation}
p(\epsilon^{(i)})=\frac{1}{\sqrt{2\pi\sigma}} e^{-\frac{ \left( \epsilon^{(i)}\right)^2 }{2\sigma ^2}}
\end{equation}

Escribiendo, lo anterior en terminos de la probabilidad de obtener un valor de $y^{i}$ dado un $x^{i}$ parametrizado por $\theta$ obtenemos que:


\begin{equation}
p_i(y^{i}|x^{i};\theta)=\frac{1}{\sqrt{2\pi\sigma}} e^{-\frac{ \left( y_i - \Theta^T X^{(i)} \right)^2 }{2\sigma ^2}}
\end{equation}



Si ausmimos independencia estadística de cada $\epsilon^{(i)}$, la probabilidad $L(\theta)$ asociada a toda la distribución de puntos viene dada por:

\begin{equation}
\cal{L}(\theta) = p(\vec{y}|X;\theta)=\prod_{i=1}^{n} p_i(y^{i}|x^{i};\theta)
\end{equation}



\begin{equation}
\cal{L}(\theta) =\prod_{i=1}^{n} \frac{1}{\sqrt{2\pi\sigma}} e^{-\frac{ \left( y_i - \Theta^T X^{(i)} \right)^2 }{2\sigma ^2}}
\end{equation}

para tener la mejor estimación posible de los valores que se deben elegir de  $\theta$, se escogeran los parámetros que generan la mayor probabilidad de ocurrencia según las observaciones, es decir, aquellos valores para el cual $L(\theta)$ es máximo, si aplicamos el logaritmo natural antes de máximar tenemos que:

\begin{equation}
\ln \cal{L}(\theta) = \cal{l}(\theta) = \ln \left[\prod_{i=1}^{n} \frac{1}{\sqrt{2\pi\sigma}} e^{-\frac{ \left( y_i - \Theta^T X^{(i)} \right)^2 }{2\sigma ^2}} \right]
\end{equation}


Después de un par de pasos se puede encontrar que:

\begin{equation}
\cal{l}(\theta) = n\ln \frac{1}{\sqrt{2\pi\sigma}} - \frac{1}{2\sigma^2} \sum_{i=1}^{n} (y^{i}-\Theta^T X^{i})^2
\end{equation},

maximar $\cal{l(\theta)}$ equivale a encontrar donde  $\nabla_{\theta} \cal{l(\theta)} = 0$. Lo anterior muestra por que la elección de minimos cuadrados puede ser una buena eleccción para el analisis de los datos.

# 1.


In [28]:
import numpy as np
import pandas as pd

In [29]:
def f(x1,x2):
    y=2.1*x1-3.1*x2
    return y
x1=np.random.uniform(0,10,10)
x2=np.random.uniform(0,10,10)
y=f(x1,x2)

X=np.zeros((3,10))
Theta=np.random.uniform(0,10,3)
Theta=np.ones(3)*Theta

print(Theta)


for i in range(3):
    for j in range(len(x1)):
        
        
        if(i==1):
            X[i][j]=x1[j]
        elif(i==2):
            X[i][j]=x2[j]
        elif(i==0):
            X[i][j]=1

[8.21909486 9.64078118 5.17623353]


In [30]:
Theta_final=np.dot(np.linalg.inv(np.dot(X,X.T)),np.dot(X,y))

In [31]:
Theta_final

array([-4.97379915e-14,  2.10000000e+00, -3.10000000e+00])

# 2.

In [36]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

df = pd.DataFrame({"mean_":target, "rm":data[:,5]})


In [37]:
df

mean_     rm
0     24.0  6.575
1     21.6  6.421
2     34.7  7.185
3     33.4  6.998
4     36.2  7.147
..     ...    ...
501   22.4  6.593
502   20.6  6.120
503   23.9  6.976
504   22.0  6.794
505   11.9  6.030

[506 rows x 2 columns]

In [39]:
X=np.zeros((3,len(df["mean_"])))
for i in range(3):
    for j in range(len(df["mean_"])):
        
        
        if(i==1):
            X[i][j]=df["mean_"][j]
        elif(i==2):
            X[i][j]=df["rm"][j]
        elif(i==0):
            X[i][j]=1

In [40]:
X

array([[ 1.   ,  1.   ,  1.   , ...,  1.   ,  1.   ,  1.   ],
       [24.   , 21.6  , 34.7  , ..., 23.9  , 22.   , 11.9  ],
       [ 6.575,  6.421,  7.185, ...,  6.976,  6.794,  6.03 ]])

In [41]:
np.loadtxt("Sesion_07_housing.csv", delimiter=",").T

ValueError: could not convert string to float: 'longitude'